### ISSUE TITLE
Sth wrong with using Ollama  +qdrant：Vector dimension error: expected dim: 1536, got 768

### ISSUE THREAD

**Issue by AI-Beans** [mem0ai/mem0#1575]
### 🐛 Describe the bug

![image](https://github.com/user-attachments/assets/e25a3f14-8656-44d3-aadc-6c85906425ea)
![image](https://github.com/user-attachments/assets/64653864-d7aa-4b19-82bd-2799932cfa37)
**I use ollama embedingmodel and chatmodel，get right response 。
But response form Qdrant：Vector dimension error: expected dim: 1536, got 768
where can I config the para ？**

**Comment by teatimekon** [comment]
Me,too，after fixing bugs in mem0/llms/ollama.py and correctly make `m = Memory.from_config(config)`，i meet this bug while using `result = m.add()`

**Comment by teatimekon** [comment]
> ### 🐛 Describe the bug
> ![image](https://private-user-images.githubusercontent.com/58964439/351659235-e25a3f14-8656-44d3-aadc-6c85906425ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTI2ODEsIm5iZiI6MTcyMTg5MjM4MSwicGF0aCI6Ii81ODk2NDQzOS8zNTE2NTkyMzUtZTI1YTNmMTQtODY1Ni00NGQzLWFhZGMtNmM4NTkwNjQyNWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA3MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwN2VkMTJhYWEyZDA5YzY2OTkwMWJmNGZkODMyZThhY2JjNTZkZjMxMWZlZTU5N2U3MTBiMWFhNjVmMjAxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m1TvQsxeyI0gmIH665HgcgHyvfXmNI5uIsaL7sGw2No) ![image](https://private-user-images.githubusercontent.com/58964439/351659274-64653864-d7aa-4b19-82bd-2799932cfa37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTI2ODEsIm5iZiI6MTcyMTg5MjM4MSwicGF0aCI6Ii81ODk2NDQzOS8zNTE2NTkyNzQtNjQ2NTM4NjQtZDdhYS00YjE5LTgyYmQtMjc5OTkzMmNmYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA3MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZjFkYzFiOTFiZDM0MDdjMTNlOTQ2YTE2NTkwMjdjYjY0OWI0NmU4NTQwNzBhZTFmNDU2YjZmNTI2YmNmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V8-B3lc0FxX9RGb1hcjlSgBCmP8dZFVJqqXoaoue7mE) **I use ollama embedingmodel and chatmodel，get right response 。 But response form Qdrant：Vector dimension error: expected dim: 1536, got 768 where can I config the para ？**

just restart the qdrant Docker can fix this bug ,see #712

**Comment by KKD4Soei** [comment]
Rebooted, but still having the same issue！

**Comment by teatimekon** [comment]
> Rebooted, but still having the same issue！

try edit mem0/embeddings/ollama.py    in line 9
```class OllamaEmbedding(EmbeddingBase):
    def __init__(self, model="nomic-embed-text"):
        self.model = model
        self._ensure_model_exists()
        self.dims = 768  #this is mine
        ```

**Comment by KKD4Soei** [comment]
config = {
    "vector_store": {
        "provider": "qdrant",
        "config": {
            "host": "localhost",
            "port": 6333,       
        }
    },
    have you changes this config？

**Comment by teatimekon** [comment]
nope

**Comment by KKD4Soei** [comment]
Is there anything else that needs to be set up?

**Comment by teatimekon** [comment]
Is there anything else that needs to be set up?

I modified a very small portion of the source code based on the error message, but the fact is that mem0 currently does not support local ollama operation

**Comment by KKD4Soei** [comment]
> Is there anything else that needs to be set up?
> 
> I modified a very small portion of the source code based on the error message, but the fact is that mem0 currently does not support local ollama operation

OK  Then I won't take the time to make it happen. I used openai first, and the effect was not bad！

Could you offer you email or wechat account, We can discuss it together

**Comment by yslion** [comment]
just create a new  'collection_name'  ， by default, the   'collection_name'  is  'mem0' (see : class MemoryItem )  , dims  is 1536 .   different  config   ,different  collection_name :)

**Comment by johnwlockwood** [comment]
The [docs](https://docs.nomic.ai/atlas/embeddings-and-retrieval/text-embedding) for the embedding model `nomic-embed-text:latest` shows it's dims are 768. So config the vector_store's embedding_model_dims to 768.
```
"vector_store": {
        "provider": "qdrant",
        "config": {
            "collection_name": "test",
            "host": "localhost",
            "port": 6333,
            "embedding_model_dims": 768,  # Change this according to your local model's dimensions
        },
    },
```
If you have already created the collection, which you have by the time you got this error, then either delete the collection in the [Qdrant UI](http://localhost:6333/dashboard#/collections) or change the collection_name so it will make a new one during Memory.add

**Comment by parshvadaftari** [comment]
Closing as fixed

**Comment by nerdyabhi** [comment]
getting same issue with typescript sdk : 

```
const config = {
  llm: {
    provider: "groq",
    config: {
      model: "llama-3.1-8b-instant",
      temperature: 0.1,
      max_tokens: 1000,
    },
  },
  embedder: {
    provider: "google",
    config: {
      apiKey: process.env.GEMINI_API_KEY!,
      model: "gemini-embedding-001",
      embeddingDims: 768,
      embedding_dims: 768,
      embedding_model_dims: 768,
    },
  },
  vectorStore: {
    provider: "qdrant",
    config: {
      collectionName: "abhi-new-test",
      embeddingModelDims: 768,
      host: "localhost",
      port: 6333,
    },
  },
  version: "v1.1",
};

```

tried whole day figuring this out !!
```

             throw new fun.Error(err);
                      ^
ApiError: Bad Request
    at Object.fun [as searchPoints] (file:///home/abhi/abhi-projects/genAI/node_modules/.pnpm/@qdrant+openapi-typescript-fetch@1.2.6/node_modules/@qdrant/openapi-typescript-fetch/dist/esm/fetcher.js:169:23)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async QdrantClient.search (file:///home/abhi/abhi-projects/genAI/node_modules/.pnpm/@qdrant+js-client-rest@1.16.2_typescript@5.9.3/node_modules/@qdrant/js-client-rest/dist/esm/qdrant-client.js:167:26)
    at async Qdrant.search (file:///home/abhi/abhi-projects/genAI/node_modules/.pnpm/mem0ai@2.1.38_@anthropic-ai+sdk@0.27.3_encoding@0.1.13__@cloudflare+workers-types@4.202_73eb170a988c6a467084e35c8e96c8d9/node_modules/mem0ai/src/oss/src/vector_stores/qdrant.ts:124:21)
    at async _Memory.addToVectorStore (file:///home/abhi/abhi-projects/genAI/node_modules/.pnpm/mem0ai@2.1.38_@anthropic-ai+sdk@0.27.3_encoding@0.1.13__@cloudflare+workers-types@4.202_73eb170a988c6a467084e35c8e96c8d9/node_modules/mem0ai/src/oss/src/memory/index.ts:278:32)
    at async _Memory.add (file:///home/abhi/abhi-projects/genAI/node_modules/.pnpm/mem0ai@2.1.38_@anthropic-ai+sdk@0.27.3_encoding@0.1.13__@cloudflare+workers-types@4.202_73eb170a988c6a467084e35c8e96c8d9/node_modules/mem0ai/src/oss/src/memory/index.ts:191:31)
    at async file:///home/abhi/abhi-projects/genAI/src/concepts/langraph/mem0.ts:59:1 {
  headers: Headers {},
  url: 'http://localhost:6333/collections/abhi-new-test/points/search',
  status: 400,
  statusText: 'Bad Request',
  data: {
    status: {
      error: 'Wrong input: Vector dimension error: expected dim: 1536, got 768'
    },
    time: 0.000357633
  }
}
```

**Comment by andrewstarlike** [comment]
try this config, it will work for Gemini:

```
 config = {
        "vector_store": {
            "provider": "qdrant",
            "config": {
                "collection_name": "mem0_gemini_memories",
                "host": qdrant_host,
                "port": qdrant_port,
            }
        },
        "llm": {
            "provider": "gemini",
            "config": {
                "model": "gemini-2.5-flash-lite",
                "api_key": gemini_api_key,
                "temperature": 0.2,
                "top_p": 1.0
            }
        },
        "embedder": {
            "provider": "gemini",  # DeepSeek also provides embeddings
            "config": {
                "model": "models/gemini-embedding-001",  # You can keep using OpenAI embeddings
                "api_key": gemini_api_key,
                "embedding_dims": 1536,
            }
        }
    }
```
