### ISSUE TITLE
Unable to setup PGVector vector store as per documentation

### ISSUE THREAD

**Issue by ggozad** [mem0ai/mem0#1740]
### 🐛 Describe the bug

Pedantic validation fails when trying to instantiate a memory using PGVector.
The following is probably the easiest way to reproduce cleanly:
```python
from mem0.vector_stores.configs import VectorStoreConfig

vector_store_config = VectorStoreConfig(
    provider="pgvector",
    config={
        "dbname": "test",
        "user": "test",
        "password": "test",
        "host": "test",
        "port": 1234,
    },
)
```
which leads to:
```python
Traceback (most recent call last):
  File "/Users/ggozad/dev/open-source/mem0/test.py", line 3, in <module>
    vector_store_config = VectorStoreConfig(
                          ^^^^^^^^^^^^^^^^^^
  File "/Users/ggozad/dev/open-source/mem0/.venv/lib/python3.12/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for VectorStoreConfig
  Value error, Extra fields not allowed: path. Please input only the following fields: dbname, host, collection_name, user, password, embedding_model_dims, port [type=value_error, input_value={'dbname': 'test', 'user'...'path': '/tmp/pgvector'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error```

**Comment by zacrafidi** [comment]
i made these changes locally and it started working. Changed:

if "path" not in config:
            config["path"] = f"/tmp/{provider}"

with: 

# Only add 'path' for providers that are not 'pgvector'
        if provider != 'pgvector' and "path" not in config:
            config["path"] = f"/tmp/{provider}"

then installing psycopg2-binary and full restarting everything and passing below to the config: 

"vector_store": {
                "provider": "pgvector",
                "config": {
                    "user": SUPABASE_DB_USER,
                    "password": SUPABASE_DB_PASSWORD,
                    "host": SUPABASE_DB_HOST,
                    "port": SUPABASE_DB_PORT,
                }
            },

**Comment by Dev-Khant** [comment]
Closing this as #1703 fixes the issue. Feel free to open it if there's still problem with it.
