### ISSUE TITLE
Error: choice in chat_completion.choices:   AttributeError: 'str' object has no attribute 'choices' with mem0ai (0.1.11)

### ISSUE THREAD

**Issue by bingjiw** [mem0ai/mem0#1838]
### 🐛 Describe the bug

```
from mem0 import Memory
import os
os.environ["OPENAI_API_KEY"] = "sk-xxxxxxxxxxxxxxxxxx"
os.environ["OPENAI_API_BASE"] = "https://api.XYZ.com"
#m = Memory()

config = {
    "llm": {
        "provider": "openai",
        "config": {
            "model": "gpt-4o",
            "temperature": 0.2,
            "max_tokens": 1500,
        }
    },
    "graph_store": {
        "provider": "neo4j",
        "config": {
            "url": "neo4j+s://xxxxxxxxxxxxxxxx.databases.neo4j.io",
            "username": "neo4j",
            "password": "xxxxxxxxxxxxxxxxx"
        }
    },
    "version": "v1.1"
}

m = Memory.from_config(config_dict=config)

m.add("Likes to play cricket on weekends", user_id="alice-test", metadata={"category": "hobbies"})

```
running the above test code with package installed:
mem0ai (0.1.11)

got error as below: 

```
(mem0test) bingji@WBJ-Mac mem0test %  cd /Users/bingji/BJ-play-AI/mem0te
st ; /usr/bin/env /Users/bingji/BJ-play-AI/mem0test/mem0test/bin/python 
/Users/bingji/.cursor/extensions/ms-python.debugpy-2024.6.0-darwin-arm64
/bundled/libs/debugpy/adapter/../../debugpy/launcher 58643 -- /Users/bin
gji/BJ-play-AI/mem0test/only_bj_test.py 
Exception in thread Thread-3 (_add_to_graph):
Exception in thread Thread-2 (_add_to_vector_store):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
    self.run()  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1012, in run

  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/memory/main.py", line 178, in _add_to_graph
        added_entities = self.graph.add(data, filters)
   self._target(*self._args, **self._kwargs)
      File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/memory/main.py", line 119, in _add_to_vector_store
                  ^response = self.llm.generate_response(^
^ ^^   ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^
^  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/memory/graph_memory.py", line 43, in add
^^^^^^^^^^^^^^^
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/llms/openai.py", line 108, in generate_response
        search_output = self._search(data, filters)return self._parse_response(response, tools)

                       ^^^^  ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/llms/openai.py", line 56, in _parse_response
^^^^^^^
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/memory/graph_memory.py", line 123, in _search
        return response.choices[0].message.content
 search_results = self.llm.generate_response(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'choices'^^
^^^^^^^^^
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/mem0/llms/openai_structured.py", line 86, in generate_response
    response = self.client.beta.chat.completions.parse(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/openai/resources/beta/chat/completions.py", line 143, in parse
    return _parse_chat_completion(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bingji/BJ-play-AI/mem0test/mem0test/lib/python3.12/site-packages/openai/lib/_parsing/_completions.py", line 70, in parse_chat_completion
    for choice in chat_completion.choices:
                  ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'choices'
(mem0test) bingji@WBJ-Mac mem0test % 
```

**Comment by bingjiw** [comment]
problem solved when switch to official openai API.
