### ISSUE TITLE
ValueError: Expected where to have exactly one operator, got {} in query.

### ISSUE THREAD

**Issue by gmdorf** [mem0ai/mem0#2039]
### 🐛 Describe the bug

This example from the docs: https://docs.embedchain.ai/api-reference/app/search, 
```
from embedchain import App

app = App()
app.add("https://www.forbes.com/profile/elon-musk")

context = app.search("What is the net worth of Elon?", num_documents=2)
print(context)

```

when used verbatim, raises this exception:

```
Traceback (most recent call last):
  File "/home/gavid/crawler_test/test1.py", line 9, in <module>
    context = app.search("What is the net worth of Elon?", num_documents=2)
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/embedchain/embedchain.py", line 712, in search
    return [{"context": c[0], "metadata": c[1]} for c in self.db.query(**params)]
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/embedchain/vectordb/chroma.py", line 221, in query
    result = self.collection.query(
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 210, in query
    query_request = self._validate_and_prepare_query_request(
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/chromadb/api/models/CollectionCommon.py", line 93, in wrapper
    raise type(e)(msg).with_traceback(e.__traceback__)
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/chromadb/api/models/CollectionCommon.py", line 90, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/chromadb/api/models/CollectionCommon.py", line 294, in _validate_and_prepare_query_request
    validate_filter_set(filter_set=filters)
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/chromadb/api/types.py", line 339, in validate_filter_set
    validate_where(filter_set["where"])
  File "/home/gavid/.asdf/installs/python/3.10.15/lib/python3.10/site-packages/chromadb/api/types.py", line 598, in validate_where
    raise ValueError(f"Expected where to have exactly one operator, got {where}")
ValueError: Expected where to have exactly one operator, got {} in query.
```

My python version: 3.10.15
My embedchain version: 0.1.125

**Comment by Cirr0e** [comment]
Hi there! I've taken a look at the issue you're experiencing with the Embedchain search method.

The error `ValueError: Expected where to have exactly one operator, got {} in query` suggests there might be an issue with how the search method is being called or how the database is configured.

Here are a few things to try:

1. Explicit Initialization:
```python
from embedchain import App
from chromadb.config import Settings

# Try specifying explicit Chroma settings
app = App(config={
    "collection_name": "my_collection",
    "persist_directory": "./chroma_db"
})
```

2. Modify Search Method:
```python
# Try specifying explicit search parameters
context = app.search("What is the net worth of Elon?", 
                     num_documents=2, 
                     where={})  # Explicitly pass an empty dict
```

3. Check Database State:
Make sure you've actually added documents to the database before searching. The example you provided adds a single URL, but ensure it's been processed:

```python
app = App()
app.add("https://www.forbes.com/profile/elon-musk")
app.query()  # Ensure database is populated

context = app.search("What is the net worth of Elon?", num_documents=2)
```

A few additional troubleshooting steps:
- Verify you're using the latest version of Embedchain
- Check that Chroma is properly installed
- Ensure you have the necessary dependencies

Could you confirm:
1. Have you successfully added documents to the database before searching?
2. What version of Chroma and Embedchain are you using?
3. Can you share the full traceback and your complete initialization code?

Let me know if any of these suggestions help or if you need more detailed guidance!

**Comment by gmdorf** [comment]
My issue is caused by a slight typo in the source code. PR here: https://github.com/mem0ai/mem0/pull/2042
