### ISSUE TITLE
[Bug] quickstart guide on dashboard does not work

### ISSUE THREAD

**Issue by robonxt-ai** [mem0ai/mem0#2105]
### 🐛 Describe the bug

It's weird, as it used to work (like two months ago), but following the quickstart guide from the [dashboard](https://app.mem0.ai/dashboard/get-started) does not work.
 
Steps I did:

1. Created a new .venv environment and load it 

2. Ran `pip install mem0ai` to install mem0

3. Ran the file `mem0.py` that contains the following:
```python 
from mem0 import MemoryClient
client = MemoryClient(api_key="your-api-key")
```

I get the following error:

```cmd
user@machine:~/project_dir$ python mem0.py 
Traceback (most recent call last):
  File "/home/user/project_dir/mem0.py", line 1, in <module>
    from mem0 import MemoryClient
  File "/home/user/project_dir/mem0.py", line 1, in <module>
    from mem0 import MemoryClient
ImportError: cannot import name 'MemoryClient' from partially initialized module 'mem0' (most likely due to a circular import) (/home/user/project_dir/mem0.py)
```

The directory is as follows:

```
project_dir/
- .venv/
- mem0.py
```

Any advice would be appreciated!

**Comment by nathubs** [comment]
The same to me!

**Comment by Dev-Khant** [comment]
Hey @robonxt-ai @nathubs It's happening because you have named your file as `mem0.py` which is causing a circular import issue. Please rename the file to something else and it should work ideally.

Closing this issue as it' a easy fix and not an issue from mem0 side. Feel free to open if you still face this issue.
