### ISSUE TITLE
An instance of Chroma already exists for db:8000 with different settings

### ISSUE THREAD

**Issue by denisj** [mem0ai/mem0#858]
### 🐛 Describe the bug

After moving from 0.4.14 to .0.4.15, I see this error all the time when I try to connect to DB in my celery workers.

chroma 0.4.15
chromadb 0.4.15
python 3.11
docker-compose

```
api_1            | INFO:     192.168.32.8:58518 - "GET /api/v1/queries?question=Did%20ukraine%20on%20war?&call_gpt=false&collection_name=cp_137 HTTP/1.0" 500 Internal Server Error
api_1            | ERROR:    Exception in ASGI application
api_1            | Traceback (most recent call last):
api_1            |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
api_1            |     return self.receive_nowait()
api_1            |            ^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
api_1            |     raise WouldBlock
api_1            | anyio.WouldBlock
api_1            | 
api_1            | During handling of the above exception, another exception occurred:
api_1            | 
api_1            | Traceback (most recent call last):
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
api_1            |     message = await recv_stream.receive()
api_1            |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
api_1            |     raise EndOfStream
api_1            | anyio.EndOfStream
api_1            | 
api_1            | During handling of the above exception, another exception occurred:
api_1            | 
api_1            | Traceback (most recent call last):
api_1            |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
api_1            |     result = await app(  # type: ignore[func-returns-value]
api_1            |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
api_1            |     return await self.app(scope, receive, send)
api_1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1115, in __call__
api_1            |     await super().__call__(scope, receive, send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
api_1            |     await self.middleware_stack(scope, receive, send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
api_1            |     raise exc
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
api_1            |     await self.app(scope, receive, _send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
api_1            |     response = await self.dispatch_func(request, call_next)
api_1            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/app/project/__init__.py", line 30, in add_no_cache_header
api_1            |     response = await call_next(request)
api_1            |                ^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
api_1            |     raise app_exc
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
api_1            |     await self.app(scope, receive_or_disconnect, send_no_error)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
api_1            |     await self.app(scope, receive, send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
api_1            |     raise exc
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
api_1            |     await self.app(scope, receive, sender)
api_1            |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
api_1            |     raise e
api_1            |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
api_1            |     await self.app(scope, receive, send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
api_1            |     await route.handle(scope, receive, send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
api_1            |     await self.app(scope, receive, send)
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
api_1            |     response = await func(request)
api_1            |                ^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
api_1            |     raw_response = await run_endpoint_function(
api_1            |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
api_1            |     return await run_in_threadpool(dependant.call, **values)
api_1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
api_1            |     return await anyio.to_thread.run_sync(func, *args)
api_1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
api_1            |     return await get_asynclib().run_sync_in_worker_thread(
api_1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
api_1            |     return await future
api_1            |            ^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
api_1            |     result = context.run(func, *args)
api_1            |              ^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/app/project/queries/routes.py", line 18, in query
api_1            |     embedchain_app = create_embedchain_app(collection_name)
api_1            |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/app/embedchain_app/__init__.py", line 37, in create_embedchain_app
api_1            |     db = ChromaDB(
api_1            |          ^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/embedchain/vectordb/chroma.py", line 60, in __init__
api_1            |     self.client = chromadb.Client(self.settings)
api_1            |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
api_1            |     return ClientCreator(tenant=tenant, database=database, settings=settings)
api_1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1            |   File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
api_1            |     super().__init__(settings=settings)
api_1            |   File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
api_1            |     SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
api_1            |   File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
api_1            |     raise ValueError(
api_1            | ValueError: An instance of Chroma already exists for db:8000 with different settings
```

**Comment by parshvadaftari** [comment]
Closing as stale.
